config/routes.rb
BookShop::Application.routes.draw do

  get "cart/add_product/:product_id" => "cart#add_product", as: :add_product
  get "cart/remove_product/:product_id" => "cart#remove_product", as: :remove_product

  post "search" => "welcome#index", as: :search

  devise_for :administrators
  devise_for :users

  get "/categories/:key" => "welcome#index", as: :categories

  namespace :admin do
    root "dashboard#index"
    resources :categories
    resources :products
  end

  root 'welcome#index'

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def add_product
    @product = Product.find(params[ :product_id])
    # Añadir al pedido
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js #{ render text: "JS" } envia texto plano
    end
  end

  def remove_product
    @product = Product.find(params[:product_id])
    # Borrar del pedido
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_product.html.erb
<li id="cart_product_<%= product.id %>">
  1 x <%= product.name %> : <%= product.decimal_price%>
  <%= link_to "(x)", remove_product_path(product), remote: true %>
</li>

app/views/cart/add_product.js.erb
$("#product_<%= @product.id %>").effect("highlight");
$("#cart").append("<%= escape_javascript(render partial: 'cart/product', locals: {product: @product}) %>");
$("#cart").effect("shake");

app/views/cart/remove_product.js.erb
$("#cart_product_<%= @product.id %>").fadeOut("slow", function() {
  $("#cart_product_<%= @product.id %>").remove();
});