config/routes.rb
BookShop::Application.routes.draw do

  get "cart/add_product/:product_id" => "cart#add_product", as: :add_product
  get "cart/remove_product/:product_id" => "cart#remove_product", as: :remove_product

  post "search" => "welcome#index", as: :search

  devise_for :administrators
  devise_for :users

  get "/categories/:key" => "welcome#index", as: :categories

  namespace :admin do
    root "dashboard#index"
    resources :categories
    resources :products
  end

  root 'welcome#index'

end

app/models/category.rb
#enconding: UTF-8
class Category < ActiveRecord::Base

  # Callbacks
  before_validation :set_downcase_key

  # Asociaciones
  has_many :products

  # Validaciones
  validates_with LikeValidator
  validates :name, :key, presence: true
  validates :key, uniqueness: true
  validates :key, format: {
    with: /\A[a-z]+\z/, message: "tiene que estar en minúsculas"
  }

private

  def set_downcase_key
    unless key.blank?
      self.key = key.sub(" ","").downcase
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to [:admin, @category], notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to [:admin, @category], notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params[:category].permit(:name, :key)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def category_link(category = Category.new(name: "todas", key: "todas"))
    content_tag :li do
      link_to "Ver #{category.name}", categories_url(category.key)
    end
  end

  def categories_link
    html = category_link
    Category.all.collect { |category|
      html += category_link(category)
    }
    html
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form_fields">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form_fields">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing admin_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_category %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>Categorias</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Clave</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.key %></td>
        <td><%= link_to 'Show', [:admin, category] %></td>
        <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
        <td>
          <%= link_to 'Destroy', [:admin, category], method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New admin_category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<dt>Nombre:</dt>
<dd><%= @category.name %></dd>

<dt>Key:</dt>
<dd><%= @category.key %></dd>

<br>
<p>
  <%= link_to 'Edit', edit_admin_category_path(@category) %> |
  <%= link_to 'Back', admin_categories_path %>
</p>