config/routes.rb
BookShop::Application.routes.draw do

  get "cart/add_product/:product_id" => "cart#add_product", as: :add_product
  get "cart/remove_product/:product_id" => "cart#remove_product", as: :remove_product

  post "search" => "welcome#index", as: :search

  devise_for :administrators
  devise_for :users

  get "/categories/:key" => "welcome#index", as: :categories

  namespace :admin do
    root "dashboard#index"
    resources :categories
    resources :products
  end

  root 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  # Callbacks
  before_validation :set_price
  before_save :set_stock_and_position

  # Asociaciones
  belongs_to :category

  # Validaciones
  validates_associated :category
  validates :name, :reference, :description, :price, presence: true
  validates :reference, :price, numericality: true
  validates :reference, uniqueness: true

  def decimal_price
    price / 100
  end

  class << self
    Product.column_names.each { |attr|
      define_method "find_by_#{attr}" do |value|
        find_by(attr.to_sym, value)
      end
    }
  end

private
  def set_price
    self.price = self.price * 100
  end

  def set_stock_and_position
    self.stock = 1000
    self.position = Product.all.size + 1
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    # OJO!!! Los StrongParemeters definen que podemos modificar
    def product_params
      params[:product].permit(:name, :description, :reference, :price, :stock)
    end
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_controls">
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </div>

  <div class="form_controls">
    <%= f.label :description %> <br>
    <%= f.text_area :description, class: "input-xlarge",rows: 2 %>
  </div>

 <div class="form_controls">
    <%= f.label :reference %> <br>
    <%= f.text_field :reference %>
  </div>

  <div class="form_controls">
    <%= f.label :price %> <br>
    <%= f.text_field :price,
                     placeholder: "0.0 €",
                     value: @product.decimal_price %>
  </div>

  <div class="form_controls">
    <%= f.label :stock %> <br>
    <%= f.text_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @product] %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Productos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= link_to 'Show', [:admin, product] %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td>
          <%= link_to 'Destroy', [:admin, product], method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<dt>Nombre:</dt>
<dd><%= @product.name %></dd>

<br>
<p>
  <%= link_to 'Edit', edit_admin_product_path(@product) %> |
  <%= link_to 'Back', admin_products_path %>
</p>