config/routes.rb
BookShop::Application.routes.draw do

  get "cart/add_product/:product_id" => "cart#add_product", as: :add_product
  get "cart/remove_product/:product_id" => "cart#remove_product", as: :remove_product

  post "search" => "welcome#index", as: :search

  devise_for :administrators
  devise_for :users

  get "/categories/:key" => "welcome#index", as: :categories

  namespace :admin do
    root "dashboard#index"
    resources :categories
    resources :products
  end

  root 'welcome#index'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
#enconding: UTF-8
class Category < ActiveRecord::Base

  # Callbacks
  before_validation :set_downcase_key

  # Asociaciones
  has_many :products

  # Validaciones
  validates_with LikeValidator
  validates :name, :key, presence: true
  validates :key, uniqueness: true
  validates :key, format: {
    with: /\A[a-z]+\z/, message: "tiene que estar en minúsculas"
  }

private

  def set_downcase_key
    unless key.blank?
      self.key = key.sub(" ","").downcase
    end
  end
end

app/models/concerns/like_validator.rb
class LikeValidator < ActiveModel::Validator

  def validate(record)
    klass = record.class
    if klass.respond_to?(:name) &&
       klass.where("name LIKE '%#{record.name}%'").size > 0
      record.errors[:name] << "tiene un valor similar"
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base

  #Callbacks
  before_create :generate_code, :init_state

  # Asociaciones
  belongs_to :user
  has_many :order_items
  has_many :products, through: :order_items

  # Validaciones
  validates_associated :user, on: :create
  validates :state, :code, :user_id, presence: true
  validates :code, uniqueness: true
  validates :code, format: { with: /Ref20[0-9]{2}_\d+/ }

  # Scopes
  scope :pending, -> { where(state: "pending") } # -> = lambda

  # State Machine
  state_machine initial: :pending do
    event :confirm do
      transition pending: :confirmed
      transition denied: :confirmed
    end

    event :pay do
      transition confirmed: :payed
    end

    event :send do
      transition payed: :sent
    end
  end

private
  def generate_code
    value = Order.where(created_at: Time.now.all_year).count + 1
    self.code = "Ref20#{Time.now.strftime("%y")}_#{value}"
  end

  def init_state
    self.state = "pending"
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base

  # Callbacks
  before_save :calculate_total_price
  after_save :destroy_if_quatity_zero

  # Asociaciones
  belongs_to :product
  belongs_to :order

  # Validaciones
  validates :product_id, :order_id, presence: true
  validates_associated :product, :order, on: :create
  validates :quatity, :total_price, presence: true
  valitates :quatity, :total_price, numericality: true {only_integer: true}

private
  def calculate_total_price
    self.total_price = product.price * self.quatity
  end

  def destroy_if_quatity_zer
    self.delete if quatity == 0
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  # Callbacks
  before_validation :set_price
  before_save :set_stock_and_position

  # Asociaciones
  belongs_to :category

  # Validaciones
  validates_associated :category
  validates :name, :reference, :description, :price, presence: true
  validates :reference, :price, numericality: true
  validates :reference, uniqueness: true

  def decimal_price
    price / 100
  end

  class << self
    Product.column_names.each { |attr|
      define_method "find_by_#{attr}" do |value|
        find_by(attr.to_sym, value)
      end
    }
  end

private
  def set_price
    self.price = self.price * 100
  end

  def set_stock_and_position
    self.stock = 1000
    self.position = Product.all.size + 1
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :customer

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_administrator!
  layout 'admin'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  ##
  #
  def index
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    # OJO!!! Los StrongParemeters definen que podemos modificar
    def product_params
      params[:product].permit(:name, :description, :reference, :price, :stock)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def add_product
    @product = Product.find(params[ :product_id])
    # Añadir al pedido
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js #{ render text: "JS" } envia texto plano
    end
  end

  def remove_product
    @product = Product.find(params[:product_id])
    # Borrar del pedido
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :user_signed_in?
  before_action :load_categories


  #
  #
  def index
    if params[:key] && Category.exists?(key: params[:key])
      @products = Category.find_by(key: params[:key]).products
    elsif params[:keyword]
      unless params[:keyword].blank?
        @products = Product.where("name like '%#{params[:keyword]}%'")
      else
        @products = Product.all
      end
    else
      @products = Product.last(10)
    end
  end

private

  #
  #
  def load_categories
    @categories = Category.all.order("name ASC")
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def category_link(category = Category.new(name: "todas", key: "todas"))
    content_tag :li do
      link_to "Ver #{category.name}", categories_url(category.key)
    end
  end

  def categories_link
    html = category_link
    Category.all.collect { |category|
      html += category_link(category)
    }
    html
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= yield :meta_desc %>
    <title>
      <%= content_for?(:title) ? yield(:title) : "BookShop" %>
    </title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Dashboard</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li>
                <%= link_to "Categorías", admin_categories_path  %>
              </li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= yield :meta_desc %>
    <title><%= content_for?(:title) ? yield(:title) : "BookShop" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= render partial: "shared/navbar" %>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <%= render partial: "shared/sidebar" %>
          </div><!--/span-->
        </div><!--/row-->

        <%= render partial: "shared/footer" %>

    </div> <!-- /container -->

  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <p>
    &copy; CiTIC 2014 -
    <%= link_to "administración", admin_root_path %>
  </p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">BookShop</a>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to "Link1", "/path1"  %></li>
          <li><%= link_to "Link2", "/path2"  %></li>
          <li><%= link_to "Link3", "/path3"  %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="well sidebar-nav">
  <h3>Search</h3>
  <%= form_tag search_path, remote: true do %>
    <%= text_field_tag :keyword %>
    <%= submit_tag "Buscar" %>
  <% end %>
  <hr>
  <h3>Sidebar</h3>
  <ul class="nav nav-list">
    <li class="nav-header">Sidebar</li>
    <%= categories_link %>
  </ul>
  <% if administrator_signed_in? %>
    <%= link_to "Log Out",
        destroy_administrator_session_path,
        method: :delete %>
  <% end %>
  <hr>
  <h3>Carrito</h3>
  <ul class="nav nav-list" id="cart">

  </ul>
  Total: <span id="total_price">0.0€</span>
</div>